#!/usr/bin/env bash
# A function that shows info about a subdomain

display_info () {
	if [ -z "$2" ]
	then
		arr="www lb-01 web-01 web-02"
		for i in $arr
		do
			dig "$i.$1" | grep -A4 'ANSWER SECTION:'\
				| awk 'NR== 2 {print "The subdomain", subdomain, "is a", $4,"record and points to", $5  }' subdomain="$i"
		done
	else
		dig "$2.$1" | grep -A4 'ANSWER SECTION:'\
			| awk 'NR==2 {print "The subdomain", arg1, "is a", $4,"record and points to", $5}' arg1="$2"
	fi
}

display_info "$1" "$2"
