#!/usr/bin/env bash
# A function that shows info about a subdomain
show_info() {
	local domain="$1"
	local subdomain="$2"
	local result
	result=$(dig +short "$subdomain.$domain")
	local record_type
	record_type=$(echo "$result" | awk '{print $4}')
	local destination
	destination=$(echo "$result" | awk '{print $1}')
	# Display the information
	echo "The subdomain $subdomain is a A $record_type record and points to $destination"
}
if [ $# -eq 1 ]; then
	domain="$1"
	# Display information for default subdomains
	show_info "$domain" "www"
	show_info "$domain" "lb-01"
	show_info "$domain" "web-01"
	show_info "$domain" "web-02"
elif [ $# -eq 2 ]; then
	domain="$1"
	subdomain="$2"
	# Display information for the specified subdomain
	show_info "$domain" "$subdomain"
else
	# Display an error message for incorrect usage
	echo "Usage: $0 <domain> [subdomain]"
	exit 1
fi
