#!/usr/bin/env bash
# A function that shows info about a subdomain
show_info() {
	local domain="$1"
	local subdomain="$2"
	local result
	result=$(dig +short "$subdomain.$domain")
	if [ -n "$result" ]; then
		local record_type
		record_type=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:$/ {getline; print $4}')
		local destination
		destination=$(dig +short "$subdomain.$domain" | head -n 1)
		# Display the information
	echo "The subdomain $subdomain is a $record_type record and points to $destination"
else
	echo "Error: Unable to retrieve DNS information for $subdomain.$domain"
	fi

}
if [ $# -eq 1 ]; then
	domain="$1"
	for subdomain in www lb-01 web-01 web-02; do
		show_info "$domain" "$subdomain"
	done
elif [ $# -eq 2 ]; then
	 domain="$1"
	 subdomain="$2"
	 show_info "$domain" "$subdomain"
 else
	 echo "Usage: $0 <domain> [subdomain]"
	 exit 1
fi
