#!/usr/bin/env bash

# Configures a new server by installing Nginx listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page,
# using curl, it returns a page that contains the string Hello World!

sudo apt-get update -y

# uses -y flag to yes all prompts during installation

sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
