#!/usr/bin/env bash
# Configures a new server by installing Nginx listening on port 80

sudo apt-get update -y
# uses -y flag to yes all prompts during installation
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
