#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me redirects to another page

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sudo sed -i '/location \/redirect_me\/ {/ {
    N; s/location \/redirect_me\/ {\n/    location \/redirect_me\/ {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }\n/ 
}' /etc/nginx/sites-available/default

sudo nginx -t
sudo ufw allow 'NGINX Full'

sudo service nginx restart
