#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me redirects to another page

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

replacement="server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default

sudo nginx -t
sudo ufw allow 'NGINX Full'

sudo service nginx restart
