#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me redirects to another page
sudo apt-get update
sudo apt-get install -y nginx

replacement="server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-available/default

sudo service nginx restart
