#!/usr/bin/env bash
# Creates a custom 404 page that contains the string Ceci n'est pas une page

if ! nginx -v &>/dev/null; then
	sudo apt-get update -y
	sudo apt-get install -y nginx
fi

echo "Hello World!" > /var/www/html/index.html

str="server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name _;/$str/" /etc/nginx/sites-available/default

sudo sed -i '/http {/a \
	error_page 404 /404_custom_error.html;\n\
	location = /404_custom_error.html {\n\
	internal;\n\
	root /usr/share/nginx/html;\n\
	return 404 "Ceci n'\''est pas une page";\n\
}\n' /etc/nginx/nginx.conf

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404_custom_error.html >/dev/null
udo fw allow 'NGINX Full'

sudo service nginx restart
