#!/usr/bin/env bash
# Creates a custom 404 page that contains the string Ceci n'est pas une page

if ! nginx -v &>/dev/null; then
	sudo apt-get update -y
	sudo apt-get install -y nginx
fi

echo "Hello World!" > /var/www/html/index.html

str="server_name _;\n\tlocation \/redirect_me {\n\t\t return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name _;/$str/" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement="\\
\terror_page 404 /404.html;\\
\tlocation = /404.html {\\
\t\troot /var/www/html;\\
\t\tinternal;\\
\t}"
sudo sed -i '/listen 80 default_server;/a '"$replacement"'' /etc/nginx/sites-available/default

sudo ufw allow 'NGINX Full'

sudo service nginx restart
