#!/usr/bin/env bash
# Configures HAproxy on 1 server to send traffic to other servers
sudo apt-get update
sudo apt-get install -y haproxy

cat <<EOL >> /etc/haproxy/haproxy.cfg
frontend http_front
        bind *:80
        stats uri /haproxy?stats
        default_backend http_back

backend http_back
        balance roundrobin
        server web-01 315017-web-01-54.227.197.97:80 check
        server web-02 315017-web-02-54.175.205.247:80 check
EOL
sed -i 's/\[315017\]/your_student_id/g' /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
sudo systemctl enable haproxy
