#!/usr/bin/env bash
# Parses Apache files and does the following:
  # Groups visitors by IP, HTTP status code.
  # Displays the num of occurrences, IP, HTTP status

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn

