#!/usr/bin/env bash
# Installs ufw and only opens 80. 443 and 22 ports

sudo apt-get update -y
sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable 80
sudo ufw enable 443
sudo ufw enable 22
sudo ufw enable -y
sudo ufw status
