#!/usr/bin/env bash
# commsnds used to debug

# list all running docker containers
sudo docker ps

# confirm port availability
sudo lsof -i :8080

# Stops all processes using port 8080
sudo kill "PID"

# Rerun the docker container again
sudo docker run -p 8080:80 -d -it holbertonschool/265-0

# get inside the container
sudo docker exec -it "container_id" /bin/bash

# check apache status
sudo service apache2 status

# Activate apache
sudo service apache2 restart

# exit container
exit
