#!/usr/bin/env bash
# A script that changes user to nginx, changes defualt port to 8080 and restarts
nginx_conf="/etc/nginx/nginx.conf"
sed -i "s/#user www-data/user nginx/" "$nginx_conf"
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 "$nginx_conf"
sudo nginx -s reload
