#!/usr/bin/env bash
# A script that changes user to nginx, changes defualt port to 8080 and restarts
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo nginx -s reload
